services:
  - type: web
    name: manpro-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn daily:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: db_proyek
